spring.application.name=IntelliCare
# Connection URL for SQL Server using the Microsoft JDBC driver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=IntelliCare;encrypt=false;

# Database username and password
spring.datasource.username=sa
spring.datasource.password=123

# Use the Microsoft SQL Server JDBC driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings suitable for Microsoft SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
# Physical naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# MQTT broker connection URL (local broker on port 1883)
mqtt.broker.url=tcp://localhost:1883
# MQTT topic for scale results
mqtt.topic.result=intellicare/scale/result

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-server.vn:8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cafemanagement1905@gmail.com
spring.mail.password=glkp cqxm zfel sauu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true