; ==========================================================
; CAU HINH CHUNG
; ==========================================================
[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600

; --- MO KHOA BO NHO FLASH ---
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_8MB.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    pololu/VL53L1X@^1.3.1

[env:workshop_app]
build_src_filter = +<*>
