; ==========================================================
; CẤU HÌNH CHUNG
; ==========================================================
[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600

; --- MỞ KHÓA BỘ NHỚ FLASH ---
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_8MB.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bogde/HX711@^0.7.5
    bblanchon/ArduinoJson@^6.21.3
[env:main_app]
build_src_filter = +<*> -<calibrate_main.cpp>

[env:calibration_app]
build_src_filter = -<*> +<calibrate_main.cpp>